### Find All Video
GET http://localhost:4000/api/v1/videos?title=stanley
Accept: application/json

### Find product by Video ID
GET http://localhost:4000/api/v1/videos/7aaMy19tHVE/products
Accept: application/json

### Find comment by Video ID
GET http://localhost:8000/api/v1/videos/video1/comments
Accept: application/json

### Create Comment
POST http://localhost:8000/api/v1/videos/video1/comments
Accept: application/json
Content-Type: application/json

{
  "username": "Ikhsan Darul",
  "comment": "Generasi GiGih"
}